name = "agent-execution-log-parser"
main = "src/index.js"

# Worker settings
compatibility_date = "2024-02-26"
workers_dev = true
send_metrics = true

# Compatibility settings
compatibility_flags = [
  "nodejs_compat" # Enables Node.js compatibility features
]

# Triggers configuration
triggers = { crons = [] } # Add cron triggers if needed

# Environment configurations
[env.production]
name = "agent-execution-log-parser"
route = { pattern = "agent-execution-log-parser.david-pacold.workers.dev", custom_domain = false }
# account_id is set via CLOUDFLARE_ACCOUNT_ID environment variable during deployment

# Environment variables for production
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.3"
MAX_LOG_SIZE_MB = "10"

[env.preview]
name = "agent-execution-log-parser-preview"
# account_id is set via CLOUDFLARE_ACCOUNT_ID environment variable during deployment
# Modern routing configuration for preview environment
# routes = [
#   { pattern = "preview.agent-execution-log-parser.david-pacold.workers.dev/*", zone_name = "david-pacold.workers.dev" }
# ]

# Environment variables for preview
[env.preview.vars]
ENVIRONMENT = "preview"
API_VERSION = "1.0.3"
MAX_LOG_SIZE_MB = "10"

# Observability configuration
[observability]
enabled = true

# Define secrets (secrets are never included in the code)
# [secrets]
# list secrets here that will be manually added with `wrangler secret put`
# example: AUTH_TOKEN

# Commented out sections that require specific account setup
# ========================================================

# KV namespaces - Uncomment and set ID when needed
# [[kv_namespaces]]
# binding = "LOGS_KV"
# id = "xxxxx" # Replace with actual KV namespace ID

# Durable Objects - Uncomment when implementing persistent storage
# [[durable_objects.bindings]]
# name = "LOG_STORAGE"
# class_name = "LogStorage"
# [[migrations]]
# tag = "v1" # Should be unique for each migration
# new_classes = ["LogStorage"]

# D1 Database - Uncomment when adding database functionality
# [[d1_databases]]
# binding = "DB"
# database_name = "logs_database"
# database_id = "xxxxx" # Get this from Cloudflare dashboard

# R2 Storage - Uncomment when adding file storage
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "log-files"
# preview_bucket_name = "log-files-preview" # Optional, for preview environment

# Queues - Uncomment when implementing background processing
# [[queues.producers]]
# binding = "LOG_QUEUE"
# queue = "log-processing-queue"