name = "agent-execution-log-parser"
main = "src/index.js"
compatibility_date = "2024-02-26"

# Environment configurations
[env.production]
name = "agent-execution-log-parser"

[env.preview]
name = "agent-execution-log-parser-preview"

# wrangler.toml (wrangler v3.88.0^)
[observability]
enabled = true